language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/
    - $TRAVIS_BUILD_DIR/.stack-work/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal --install-ghc build --only-dependencies

install: true

script:
  - stack --no-terminal install
