language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - git-core

    - os: osx
      osx_image: xcode9

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install xz
      travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi

install:
  - stack --no-terminal build --test --no-run-tests --haddock --haddock-deps

script:
  - cd ghc-alter

  - cd boot-lib

  - cd integer-gmp
  - autoreconf -i
  - cd ..

  - cd base
  - autoreconf -i
  - cd ..

  - cd ..

  - cd ..
  
  - stack --no-terminal test ghc-alter:compile-fact
  - stack --no-terminal test ghc-alter:ghc-alter-boot

  - |
    if [ `uname` = "Linux" ]
    then
      cd `stack path --local-doc-root`
      touch .nojekyll
      git init
      git checkout -b gh-pages
      git add --all
      git commit --message="Initial commit"
      git push https://TerrorJack:$GITHUB_ACCESS_TOKEN@github.com/TerrorJack/ghc-alter.git gh-pages --force
    fi
