language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - git-core

    - os: osx
      osx_image: xcode9

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install xz
      travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi

install:
  - cd ghc-alter/boot-lib/integer-gmp
  - autoreconf -i
  - cd ../base
  - autoreconf -i
  - cd $TRAVIS_BUILD_DIR
  - stack --no-terminal setup
  - curl -L https://github.com/TerrorJack/ghc-doc/archive/gh-pages.zip -o ghc-doc.zip
  - unzip ghc-doc.zip
  - mv ghc-doc-gh-pages html
  - cp -r html `stack path --programs`/ghc-8.2.1/share/doc/ghc-8.2.1/
  - stack --no-terminal build --test --no-run-tests --haddock --haddock-deps
  - stack --no-terminal test ghc-alter:compile-fact
  - stack --no-terminal test ghc-alter:ghc-alter-boot

script:
  - |
    if [ `uname` = "Linux" ] && [ $TRAVIS_REPO_SLUG == "TerrorJack/ghc-alter" ]
    then
      cd `stack path --local-doc-root`
      touch .nojekyll
      git init
      git checkout -b gh-pages
      git add --all
      git commit --message="Auto-generated haddock documentation of commit $TRAVIS_COMMIT"
      git push https://TerrorJack:$GITHUB_ACCESS_TOKEN@github.com/TerrorJack/ghc-alter.git gh-pages --force
    fi
