language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      group: edge
      addons:
        apt:
          sources:
            - git-core
            - hvr-ghc
            - ubuntu-toolchain-r-test
          packages:
            - ghc-head
            - ghc-head-htmldocs

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:/opt/ghc/head/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - cd ghc-alter/boot-lib/integer-gmp
  - autoreconf -i
  - cd ../base
  - autoreconf -i
  - cd $TRAVIS_BUILD_DIR
  - stack --no-terminal build --test --no-run-tests --haddock --haddock-deps
  - stack --no-terminal test ghc-alter:compile-fact
  - stack --no-terminal test ghc-alter:ghc-alter-boot

script:
  - |
    if [ $TRAVIS_REPO_SLUG == "TerrorJack/ghc-alter" ]
    then
      cd `stack path --local-doc-root`
      touch .nojekyll
      git init
      git checkout -b gh-pages
      git add --all
      git commit -q --message="Auto-generated haddock documentation of commit $TRAVIS_COMMIT"
      git push https://TerrorJack:$GITHUB_ACCESS_TOKEN@github.com/TerrorJack/ghc-alter.git gh-pages --force
    fi
