shallow_clone: true

cache:
  - "%APPDATA%\\stack"
  - "%APPVEYOR_BUILD_FOLDER%\\.stack-work"

install:
  - cinst haskell-stack

before_build:
  - stack setup > NUL
  - stack exec pacman -- -S autoconf --noconfirm
  - stack --no-terminal build --only-dependencies

build_script:
  - stack --no-terminal build

test_script:
  - stack --no-terminal test
