name: ghc-kit
version: 0.0.1
category: Compiler
synopsis: Utilities for building Haskell tooling with ghc.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/ghc-kit

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

  - test/fact.hs
  - test/FactFunc.hs

other-extensions:
  - DefaultSignatures
  - DeriveGeneric
  - DeriveLift
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - RecordWildCards
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TypeOperators

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - binary
  - Cabal
  - directory
  - filepath
  - ghc
  - process
  - template-haskell
  - transformers

custom-setup:
  dependencies:
    - base
    - binary
    - Cabal

library:
  source-dirs: src

executables:
  ghc-wrapper:
    source-dirs: app
    main: ghc-wrapper.hs
    dependencies:
      - ghc-kit

tests:
  ghc-kit-boot:
    source-dirs: test
    main: ghc-kit-boot.hs
    dependencies:
      - ghc-kit
  
  compile-fact:
    source-dirs: test
    main: compile-fact.hs
    dependencies:
      - ghc-kit
