resolver: ghc-8.3.20170902
system-ghc: true
skip-ghc-check: true
ghc-build: standard
packages:
  - ghc-alter
  - ghc-alter-buildinfo
  - ghc-alter-eval
  - ghc-alter-frontend
  - ghc-alter-store
  - ghc-alter-with-ir
