name: ghc-alter-store
version: 0.0.1
category: Compiler
synopsis: A simple object file store.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/ghc-alter

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base
  - directory
  - filepath
  - ghc == 8.2.1

library:
  source-dirs: src
