name: ghc-alter
version: 0.0.1
category: Compiler
synopsis: Utilities for building Haskell tooling with ghc.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/ghc-alter

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

  - test/fact/fact.hs
  - test/fact/FactFunc.hs

other-extensions:
  - DeriveLift
  - GADTs
  - NamedFieldPuns
  - RecordWildCards
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell

ghc-options: -Wall

dependencies:
  - base >= 4.10 && < 5
  - binary
  - Cabal == 2.0.0.2
  - containers
  - directory
  - filepath
  - ghc == 8.2.1
  - ghc-alter-print-ir
  - ghc-alter-store
  - ghc-alter-with-ir
  - hoopl
  - process
  - template-haskell
  - pretty-show

custom-setup:
  dependencies:
    - base >= 4.10 && < 5
    - binary
    - Cabal == 2.0.0.2
    - filepath

library:
  source-dirs: src

executables:
  ghc-wrapper:
    source-dirs: app
    main: ghc-wrapper.hs
    dependencies:
      - ghc-alter

tests:
  ghc-alter-boot:
    source-dirs: test
    main: ghc-alter-boot.hs
    dependencies:
      - ghc-alter
  
  compile-fact:
    source-dirs: test
    main: compile-fact.hs
    dependencies:
      - ghc-alter
