name: ghc-alter
version: 0.0.1
category: Compiler
synopsis: Utilities for building Haskell tooling with ghc.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/ghc-alter

data-files:
  - boot-lib/**/*

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

  - test/fact/fact.hs
  - test/fact/FactFunc.hs

ghc-options: -Wall

dependencies:
  - base
  - binary
  - Cabal
  - containers
  - directory
  - filepath
  - ghc
  - ghc-alter-buildinfo
  - ghc-alter-orphans
  - ghc-alter-store
  - ghc-alter-with-ir
  - hoopl
  - process
  - template-haskell
  - pretty-show

custom-setup:
  dependencies:
    - base
    - Cabal
    - ghc-alter-buildinfo

library:
  source-dirs: src
  other-extensions:
    - DeriveLift
    - MagicHash
    - RecordWildCards
    - StandaloneDeriving
    - TemplateHaskell

executables:
  ghc-wrapper:
    source-dirs: app
    main: ghc-wrapper.hs
    dependencies:
      - ghc-alter

tests:
  ghc-alter-boot:
    source-dirs: test
    main: ghc-alter-boot.hs
    dependencies:
      - ghc-alter

  compile-fact:
    source-dirs: test
    main: compile-fact.hs
    dependencies:
      - ghc-alter
