name: ghc-alter-frontend
version: 0.0.1
category: Compiler
synopsis: Utils for building ghc frontend plugins.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/ghc-alter

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base
  - ghc

library:
  source-dirs: src
  other-extensions:
    - RecordWildCards
