name: ghc-alter-unexported
version: 0.0.1
category: Compiler
synopsis: Unexported functions from ghc.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/ghc-alter

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wno-name-shadowing

dependencies:
  - array
  - base
  - bytestring
  - containers
  - ghc
  - ghci

library:
  source-dirs: src
